### ISSUE TITLE
About the details of the evaluation

### ISSUE THREAD

**Issue by Liu-Xinhang** [nv-nguyen/pizza#2]
Hello, though feeling very impressive to read such excellent work, I have a question about how to evaluate the metrics like ADD(S), K° Kcm, proj2d. I mean, you estimate the relative transformation between the consecutive frames, so the result could be worse and worse with a long term tracking because of the accumulation of errors. So when evaluating the results, are there any methods to re-localization the object or just use the ground-truth pose regularly? If the result comes with no re-localization procedure. How long can this pipeline track? Thanks.

**Comment by nv-nguyen** [comment]
Hi @Liu-Xinhang, 

Thanks for you interest in our paper!

As detailed in the paper, we follow previous works for all of our evaluation: 

- The results in table 2 are done with ADD(S), K° Kcm, Proj2d in two frames settings (i.e there is 1 relative pose for each sequence ~ no tracking) as done in DeepIM.
- The results in table 3 and 4 are done with re-initialization with GT poses for every 15 frames as done in Laval.
- The results in table 5 are done without re-initialization as done in LatentFusion.

As you mentioned, there is an accumulation of errors for a long term tracking for the evaluation in table 3, 4, 5 but we just follow previous works and did not create any new setting to correct this accumulation of errors.

Hope it will be helpful!

Nguyen

**Comment by Liu-Xinhang** [comment]
Thanks for your reply , now I clearly understand😊.
